### PR TITLE
Payload and general swift improvements

### PR DESCRIPTION
**Pull request by siemensikkema**
- merges PayloadBuilder and Payload
- add type safe access to Payload properties
- use guard syntax where applicable
- use Swift error handling instead of returning optional InvalidTokens
- rename Test classes
- simplified Date verification error handling
- consistent colon/space syntax

### CODE REVIEW

**Comment by kylef** [comment]
Thanks for the pull request @siemensikkema. I'm a little busy at the moment but I'll try and review these changes in the next few days.

**Comment by kylef** [comment]
Sorry for the delay on this one @siemensikkema. Would you be able to update the README examples to still work with your changes please.

**Comment by nickskull** [comment]
@siemensikkema It would be great if this could get merged in! 🎉  Do you need help with finishing up the README as @kylef mentioned? :)

**Comment by kylef** [comment]
Thanks again for this pull request @siemensikkema, I've manually merged most of these changes in but I've made some changes:

- Named `ClaimSet` not `Payload` to better match the naming conventions in the JWT RFC.
- Not broken any existing public APIs.

See https://github.com/kylef/JSONWebToken.swift/commit/ce7285f72150910440857dde53f29ef09718906d for documentation / CHANGELOG changes describing.

**Comment by siemensikkema** [comment]
Looks good! I wanted to respond and help you with the changes but I hadn't yet found the time. I think ClaimSet is a great name although it is possible and useful to include other information there that are not strictly claims.

**Pull request closed without merging**
