### PR TITLE
Remove deprecated encode/decode methods, fix warnings and other…

### PR DESCRIPTION
**Pull request by jonblatho**
Summary of what’s changed:

* Removed deprecated encode/decode methods; this should make usage of these methods much more pleasant as the `ClaimSet` type will no longer need to be given explicitly
* Bumped CryptoSwift version to 0.10.0
* Resolved the warning about `deallocate(capacity:)` deprecation
* Renamed `validateExpiary(leeway:)` to `validateExpiry(leeway:)` — the old misspelled method is still available but deprecated
* Updated decoding unit tests to use `ClaimSet` instead of `Payload`
* Updated encoding unit tests to account for unordered Swift dictionaries — this was causing unwarranted test failures
* Update LinuxMain.swift for new unit tests
* Account for CommonCrypto inclusion in Swift 4.2 in Package.swift (allows for builds in Xcode 10 beta and going forward)

With all that said, this PR alone would probably make for a decent 3.0 release given the code-breaking change at the top of the list. Perhaps also consider #99/#106; it’s a quick-and-easy change that people seem to want.

### CODE REVIEW

**Comment by jonblatho** [comment]
Swift 4 deprecates `deallocate(capacity:)`, but CI builds are failing because `deallocate` is missing an argument for capacity.

Interesting…are the CI builds _really_ using Swift 4?

I’ve tested the following configs and the package successfully compiled with no warnings on each of:
* Ubuntu 16.04, Swift 4.1.2
* Ubuntu 16.04, Swift 4.2
* macOS Mojave, Swift 4.2

**Comment by jakekrog** [comment]
@jonblatho I tried out your changes, but when running `carthage update --platform ios` I get this:

```
*** Skipped building JSONWebToken.swift due to the error:
Dependency "JSONWebToken.swift" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/jonblatho/JSONWebToken.swift/issues/new
```

**Comment by jonblatho** [comment]
@jakekrog I unfortunately don’t really have any experience with Carthage at all, let alone enough to handle issues with it. I’m sorry!

**Comment by jakekrog** [comment]
@jonblatho It was actually my mistake, I didn't realize that the project file had been removed in the master branch.

**Comment by plflanagan** [comment]
Is this going to be reviewed/merged any time soon?

**Comment by kylef** [comment]
Thanks @jonblatho!

**Pull request merged**
