### PR TITLE
Add tvOS deployment target

### PR DESCRIPTION
**Pull request by maxfell**
This allows JSONWebToken.swift to be added to tvOS projects.

### CODE REVIEW

**Comment by maxfell** [comment]
seems like there is something odd with the Travis configuration

**Comment by kylef** [comment]
@maxfell The travis config is using Xcode 7, which obviously doesn't have tvOS support.

Would you be able to change the line in this PR so travis passes? I think either xcode72 or xcode73 should work.

https://github.com/kylef/JSONWebToken.swift/blob/master/.travis.yml#L2

```diff
- osx_image: xcode7
+ osx_image: xcode72
```

**Comment by maxfell** [comment]
Ha! It failed another time. This time due to something unrelated. I created a PR for it: https://github.com/kylef/JSONWebToken.swift/pull/24

**Comment by kylef** [comment]
I've fixed this up, squashed and merged as https://github.com/kylef/JSONWebToken.swift/commit/bc1f1ef7440bc2873c7ed0ccce43884ac743e1f1.

**Pull request closed without merging**
